### ISSUE TITLE
显示完成上传，但实际未成功

### ISSUE THREAD

**Issue by nosferatu747** [halo-sigs/plugin-alist#16]
您好，我遇到个问题
alist v3.36.0
halo v2.17.2
alist用户权限开最大，发代文件大小限制代码已加。
第一次配置好可以上传文件，第二个文件显示完成上传，但alist内实际没有文件。更换挂载目录可以上传一次文件，第二次还是显示完成上传，实际没有上传成功。就是更换挂载目录，让他新建目录同时才会成功上传文件。

**Comment by JohnNiang** [comment]
看看我这里的解释能否解答你的问题呢？

> https://github.com/halo-sigs/plugin-alist/issues/14#issuecomment-2328001230

**Comment by nosferatu747** [comment]
没有能解答我的问题哦，我不需要跳转，我可以通过校验，只是遇到了所述的奇怪问题

**Comment by JohnNiang** [comment]
Hi @nosferatu747 , 不好意思， 昨天我贴错了引用，请看[这个引用](https://github.com/halo-sigs/plugin-alist/issues/15#issuecomment-2328012651)是否有用。

**Comment by nosferatu747** [comment]
谢谢，我提问时是用的alist挂载的onedrive，我又打开onedrive观察，发现halo上传后，onedrive已经上传成功，是alist没有更新文件列表，导致halo也获取不到alist下载链接，必须上传后马上手动刷新alist才行哈。用alist挂载VPS本地目录，搭配halo没有问题哈。
