### ISSUE TITLE
ipv6创建的Alist在使用该插件创建储存仓库时无法解析域名

### ISSUE THREAD

**Issue by pureskys** [halo-sigs/plugin-alist#18]
Failed to resolve 'alist.puresky.top' [A(1)]
![image](https://github.com/user-attachments/assets/15343fda-bdee-4da4-b90c-2c6827b5a7b8)

**Comment by pureskys** [comment]
> 建议先去服务器上 dig、nslookup 或者 ping 一下该地址，看看能否正确解析。
> 
> 我这里解析的结果如下所示：
> 
> ```shell
> nslookup alist.puresky.top
> Server:		192.168.233.1
> Address:	192.168.233.1#53
> 
> Non-authoritative answer:
> *** Can't find alist.puresky.top: No answer
> ```

您好！域名在服务器上是可以ping通的。
![image](https://github.com/user-attachments/assets/75d0d325-e6f8-4c72-953a-741031cfb633)

**Comment by JohnNiang** [comment]
Hi @pureskys ，建议去 Halo 容器内 ping 一下该域名。我这边不管是在本地还是在服务器上都无法正常解析 `alist.puresky.top`，请看下面的结果：

```bash
ping alist.puresky.top
ping: alist.puresky.top: Name or service not known
```

**Comment by pureskys** [comment]
> Hi @pureskys ，建议去 Halo 容器内 ping 一下该域名。我这边不管是在本地还是在服务器上都无法正常解析 `alist.puresky.top`，请看下面的结果：
> 
> ```shell
> ping alist.puresky.top
> ping: alist.puresky.top: Name or service not known
> ```

感谢建议！
已查明原因：docker容器未开启IPv6网络支持。
解决方案：通过docker局域网连接alist或开启docker的IPv6网络支持。
