### ISSUE TITLE
提示  加载异常

### ISSUE THREAD

**Issue by konglquan** [halo-sigs/plugin-alist#21]
链接我试了可以下载下来，然后alist里面也可以预览下载。halo里就不行

http://207.211.189.252:5244/p/%E5%A4%B8%E5%85%8B/image.png?sign=t2y81lnm3eHOEXeO9XSVe-_AJwJewa7HxZsDE-qA6Ag=:0

**Comment by JohnNiang** [comment]
Closes in favor of #22 

/triage duplicate
/close
