### ISSUE TITLE
提示：加载异常

### ISSUE THREAD

**Issue by ljq7721** [halo-sigs/plugin-alist#22]
刚上传都是正常加载，第二天发现全部加载异常，重启Alist、halo,都无法正常加载
![image](https://github.com/user-attachments/assets/0343113c-7997-4b3f-b9cf-0073976b6a5c)
我Alist挂载的为天翼网盘，文件在Alist里可正常预览

**Comment by ljq7721** [comment]
新上传的可以使用，旧的依旧无法加载

**Comment by sucooer** [comment]
我也一样，上传了都没动什么设置第二天就加载异常了

**Comment by JohnNiang** [comment]
建议查看一下“加载异常”的附件详情，看看完整的附件 URL 是什么。

/triage needs-information

**Comment by AR-26710** [comment]
我也遇到这个问题，不可预览原因可能如下图所示。

图中标注1使用的是附件库的url
图中标注2使用的是alist复制的rul
![Image](https://github.com/user-attachments/assets/021584c6-188f-40f5-9577-0f09c36e42cc)

附件库的url
![Image](https://github.com/user-attachments/assets/15fb8036-c0b3-42e6-9d83-197d3ac7da4c)

alist复制的rul
![Image](https://github.com/user-attachments/assets/3a2d0a63-309a-46e4-aa46-5f2f9c5ab428)

**Comment by JohnNiang** [comment]
请问当前 Halo 版本是 2.20 吗？

**Comment by AR-26710** [comment]
> 请问当前 Halo 版本是 2.20 吗？

嗯，是的，目前测试使用的是[2.20.5](https://www.lxware.cn/docs/helpcenter/halo-pro/changlog)版本。

**Comment by SOVLOOKUP** [comment]
URL中时间戳过期

**Comment by JohnNiang** [comment]
想要彻底解决这个问题，请参考这个 Issue：<https://github.com/halo-dev/halo/issues/6961>。

事实上不推荐使用网盘作为图床，很有可能对方开启了防盗链之后，所有的图片都无法使用。所以我推荐“只存不读”这种操作。

> https://github.com/halo-sigs/plugin-alist/issues/29
