### ISSUE TITLE
无法上传文件

### ISSUE THREAD

**Issue by merryafei** [halo-sigs/plugin-alist#24]
1. 我在Alist里面正确添加了其他存储，并且填写的用户路径与Alist保持一致，报错.路径貌似都是正确的
![Image](https://github.com/user-attachments/assets/2d7eb4ef-5e0a-45b2-a4d7-5521905f319b)
![Image](https://github.com/user-attachments/assets/6403e079-3f36-4807-8405-c50875e08c38)
后来我试了蓝奏云，突然就正常了，115网盘不知道咋回事一直报错，但是在Alist是正常的
![Image](https://github.com/user-attachments/assets/baa60d58-7c33-4b82-bd2b-c9b6653d6551)

**Comment by JohnNiang** [comment]
2. 建议提供 Alist 的完整配置（移除敏感信息）。
3. 3. 第二张截图中的“请升级至最新版”提示是 Alist 服务端返回的。建议按照提示升级一下 Alist 重试。

**Comment by merryafei** [comment]
> 1. 建议提供 Alist 的完整配置（移除敏感信息）。
> 2. 第二张截图中的“请升级至最新版”提示是 Alist 服务端返回的。建议按照提示升级一下 Alist 重试。

![Image](https://github.com/user-attachments/assets/09c298c2-4de1-49ef-843c-8e7de90df23a)
插件已经是最新版本

**Comment by JohnNiang** [comment]
上面提到的升级 AList，指的是升级 AList 服务，不是 AList 插件。
