### ISSUE TITLE
halo里面的这个插件必须要经过自己搭建的alist服务器吗

### ISSUE THREAD

**Issue by wshlyl** [halo-sigs/plugin-alist#30]
halo里面的这个插件必须要经过自己搭建的alist服务器吗，阿里云盘第三方权益支持webdav，但是无法通过halo里面的alist直接访问。

**Comment by Roozenlz** [comment]
这个插件是用来适配alist服务器的，其他云盘支持webdav跟alist没关系，只能在halo里连接alist的存储
