### ISSUE TITLE
基本路径的https的s怎么没有了

### ISSUE THREAD

**Issue by Terryisthebest** [halo-sigs/plugin-alist#35]
![Image](https://github.com/user-attachments/assets/7eda55f2-bc8c-4bbd-a392-ffefe187ce28)
我挂载的时候是加了s的
![Image](https://github.com/user-attachments/assets/4d4fa983-5ae3-459e-ae1d-9e52a6d96dc7)

**Comment by Roozenlz** [comment]
下个版本再看看
