### ISSUE TITLE
AList 站点地址含有端口，但上传后图片链接的端口被删掉了

### ISSUE THREAD

**Issue by SRY-CTB** [halo-sigs/plugin-alist#36]
如题
截图如下：
![QQ20241208-004102.png](https://img-2.shanrenyi.top/image-2/2024/12/08/67547b68a5e45.png)
![QQ20241208-004217.png](https://img-2.shanrenyi.top/image-2/2024/12/08/67547b69862e4.png)

**Comment by Roozenlz** [comment]
等下个版本再看看
