### ISSUE TITLE
关于非英文文件无法加载

### ISSUE THREAD

**Issue by coolchengSAMA** [halo-sigs/plugin-alist#5]
### 一、非英文文件上传

当我通过alist存储库上传非英文文件时，Halo返回的直连会自动进行转义，导致无法读取加载图片。

![screenshot-1722441612739](https://github.com/user-attachments/assets/f88f1dc0-e9a8-4214-b93d-8bb4a4d05475)

### 二、英文文件上传

当我上传英文文件时，文件能够正常读取加载。

![screenshot-1722441586739](https://github.com/user-attachments/assets/74cac46b-73dd-4305-b96c-b85c31ec2073)

### 希望能够正常显示非英文名的文件，或者在插件页面增加相关提醒。

**Comment by Roozenlz** [comment]
貌似不进行编码可以解决这个问题

**Comment by Roozenlz** [comment]
试一试新版本
