### ISSUE TITLE
无法在编辑器中粘贴图片上传

### ISSUE THREAD

**Issue by huajiba** [halo-sigs/plugin-alist#8]
halo-dev/halo#6455
这是我在halo官方提的issue，在这里也提一个

**Comment by JohnNiang** [comment]
/kind bug

这应该属于 Alist 插件的 bug。

导致该错误的具体代码如下所示：

https://github.com/halo-sigs/plugin-alist/blob/ec2ad222143147b9143dbc9ae26dd7b7decb81b5/src/main/java/run/halo/alist/endpoint/AListAttachmentHandler.java#L125
